# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-10-11 15:19
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='image',
            field=models.FileField(null=True, upload_to='documents/%Y/%m/%d/'),
        ),
        migrations.AddField(
            model_name='user',
            name='my_tags',
            field=models.CharField(default='', max_length=255, verbose_name='my tags'),
        ),
        migrations.AddField(
            model_name='user',
            name='start_date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='user',
            name='date_of_birth',
            field=models.DateField(null=True, verbose_name='date of birth'),
        ),
        migrations.AlterField(
            model_name='user',
            name='user_name',
            field=models.CharField(max_length=30, unique=True, verbose_name='user name'),
        ),
    ]
