# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-10-11 15:19
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_auto_20181011_1519'),
        ('sites', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DayFeature',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sub_text', models.CharField(max_length=255)),
                ('time_stamp', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.RemoveField(
            model_name='site',
            name='subject',
        ),
        migrations.AddField(
            model_name='comment',
            name='votes',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='reply',
            name='votes',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='site',
            name='site_image',
            field=models.ForeignKey(blank=True, default=None, on_delete=django.db.models.deletion.CASCADE, to='home.ThemeImage'),
        ),
        migrations.AddField(
            model_name='dayfeature',
            name='site',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='sites.Site'),
        ),
    ]
