# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-10-12 17:47
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sites', '0004_site_featured'),
    ]

    operations = [
        migrations.RenameField(
            model_name='site',
            old_name='featured',
            new_name='is_featured',
        ),
    ]
