# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2019-01-08 13:30
from __future__ import unicode_literals

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('sites', '0006_auto_20181012_1758'),
    ]

    operations = [
        migrations.AlterField(
            model_name='site',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
    ]
