# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-05-30 01:00
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DayFeature',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('sub_text', models.CharField(max_length=255)),
                ('time_stamp', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.CreateModel(
            name='ThemeImage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=255)),
                ('image', models.FileField(upload_to='documents/%Y/%m/%d/')),
            ],
        ),
        migrations.AddField(
            model_name='dayfeature',
            name='theme_image',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.ThemeImage'),
        ),
    ]
