# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-10-11 15:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dayfeature',
            name='theme_image',
        ),
        migrations.AlterField(
            model_name='themeimage',
            name='image',
            field=models.ImageField(blank=True, upload_to='documents/%Y/%m/%d/'),
        ),
        migrations.DeleteModel(
            name='DayFeature',
        ),
    ]
