# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2019-01-07 05:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_lib', '0002_auto_20190105_1225'),
    ]

    operations = [
        migrations.AddField(
            model_name='folder',
            name='created_at',
            field=models.CharField(default='/mylib/', max_length=999999),
        ),
    ]
