# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2019-01-09 11:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sites', '0008_auto_20190108_1336'),
        ('my_lib', '0003_folder_created_at'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='folder',
            name='sites',
        ),
        migrations.AddField(
            model_name='folder',
            name='sites',
            field=models.ManyToManyField(to='sites.Site'),
        ),
    ]
