# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2019-01-20 06:24
from __future__ import unicode_literals

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('my_lib', '0004_auto_20190109_1150'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='folder',
            name='id',
        ),
        migrations.AddField(
            model_name='folder',
            name='universal_id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
    ]
